sudo: required
services:
  - docker

before_install:
  - docker build -t lumpa7223/react-test -f client/Dockerfile.dev ./client

script:
  - docker run -e CI=ture lumpa7223/react-test yarn test

after_success:
  - docker build -t lumpa7223/multi-client ./client
  - docker build -t lumpa7223/multi-nginx ./nginx
  - docker build -t lumpa7223/multi-server ./server
  - docker build -t lumpa7223/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push lumpa7223/multi-client
  - docker push lumpa7223/multi-nginx
  - docker push lumpa7223/multi-server
  - docker push lumpa7223/multi-worker
